// PDF 생성 유틸리티
import jsPDF from 'jspdf';

export async function generatePDF(
  userMessage: string,
  assistantMessage: string,
  conversationTitle?: string
) {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 20;
  let yPos = 20;

  // 헤더 - Ruleout AI
  doc.setFontSize(20);
  doc.setTextColor(32, 128, 141); // #20808D
  doc.text('Ruleout AI', margin, yPos);
  yPos += 12;

  // 날짜
  doc.setFontSize(10);
  doc.setTextColor(100, 100, 100);
  const date = new Date().toLocaleDateString('ko-KR', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });
  doc.text(date, margin, yPos);
  yPos += 10;

  // 대화 제목 (있는 경우)
  if (conversationTitle) {
    doc.setFontSize(12);
    doc.setTextColor(50, 50, 50);
    doc.text(conversationTitle, margin, yPos);
    yPos += 10;
  }

  // 구분선
  doc.setDrawColor(200, 200, 200);
  doc.line(margin, yPos, pageWidth - margin, yPos);
  yPos += 10;

  // 질문 섹션
  doc.setFontSize(14);
  doc.setTextColor(32, 128, 141);
  doc.text('Question:', margin, yPos);
  yPos += 8;

  doc.setFontSize(11);
  doc.setTextColor(50, 50, 50);

  // UTF-8 인코딩으로 텍스트 처리
  const questionLines = doc.splitTextToSize(
    decodeURIComponent(encodeURIComponent(userMessage)),
    pageWidth - 2 * margin
  );

  questionLines.forEach((line: string) => {
    if (yPos > pageHeight - 30) {
      doc.addPage();
      yPos = 20;
    }
    doc.text(line, margin, yPos);
    yPos += 6;
  });
  yPos += 10;

  // 답변 섹션
  doc.setFontSize(14);
  doc.setTextColor(32, 128, 141);
  doc.text('Answer:', margin, yPos);
  yPos += 8;

  doc.setFontSize(11);
  doc.setTextColor(50, 50, 50);

  // 마크다운 제거
  const plainText = assistantMessage
    .replace(/#{1,6}\s/g, '')
    .replace(/\*\*/g, '')
    .replace(/\*/g, '')
    .replace(/`{1,3}[^\n]*`{1,3}/g, '')
    .replace(/\[([^\]]+)\]\([^\)]+\)/g, '$1')
    .replace(/\n{3,}/g, '\n\n')
    .trim();

  const answerLines = doc.splitTextToSize(
    decodeURIComponent(encodeURIComponent(plainText)),
    pageWidth - 2 * margin
  );

  answerLines.forEach((line: string) => {
    if (yPos > pageHeight - 30) {
      doc.addPage();
      yPos = 20;
    }
    doc.text(line, margin, yPos);
    yPos += 6;
  });

  // 푸터
  const totalPages = doc.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    doc.setFontSize(9);
    doc.setTextColor(150, 150, 150);
    const footerText = `Page ${i} of ${totalPages} - Generated by Ruleout AI`;
    doc.text(footerText, pageWidth / 2, pageHeight - 10, { align: 'center' });
  }

  return doc;
}
